[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of the 'Vault' node for the SAFE Network."
documentation = "https://docs.rs/safe_vault"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.19.2"

[dependencies]
base64 = "~0.10.1"
# Ensure bincode version is identical to that in SAFE Client Libs and SAFE Network Data.
bincode = "=1.1.4"
bytes = { version = "~0.4.12", features = ["serde"] }
crossbeam-channel = "~0.3.8"
ctrlc = "~3.1.3"
directories = "~2.0.1"
env_logger = "~0.6.2"
fxhash = { version = "~0.2.1", optional = true }
hex = "~0.3.2"
hex_fmt = { version = "~0.3.0", optional = true }
lazy_static = "~1"
log = "~0.4.7"
pickledb = "~0.4.0"
quick-error = "~1.2.2"
rand = "~0.6.5"
# routing = { git = "https://github.com/maidsafe/routing.git", branch = "fleming" }
routing = { path = "../routing" }
safe-nd = "~0.4.0"
self_update = "0.5.1"
serde = { version = "~1.0.97", features = ["derive"] }
serde_json = "~1.0.40"
structopt = "~0.2.18"
tiny-keccak = "~1.5.0"
unwrap = "~1.2.1"

[dev_dependencies]
maplit = "~1.0.1"
rand_chacha = "~0.1.1"
tempdir = "~0.3.7"

[[bin]]
name = "safe_vault"
doc = false

[features]
mock = ["fxhash", "hex_fmt"]
mock-parsec = ["routing/mock_parsec", "routing/mock_crypto"]
phase-one = []
